### ISSUE TITLE
Deserialization exception with MongoDriver 1.8.1

### ISSUE THREAD

**Issue by aleksandrov** [Nanoko/quartznet-mongodb#9]
Hello,

Am I missed something? When I'm trying to schedule a test job:

```
IJobDetail job = JobBuilder.Create(typeof(DumbJob)).WithIdentity("dump", "AppService").Build();

ITrigger trigger =
    TriggerBuilder.Create()
                    .WithIdentity("test_trigger", "AppService")
                    .WithSimpleSchedule(x => x.WithIntervalInSeconds(20).RepeatForever())
                    .StartAt(DateBuilder.FutureDate(10, IntervalUnit.Second))
                    .Build();
scheduler.ScheduleJob(job, trigger);
```

I've got BsonSerializationException in ScheduleJob() method:

MongoDB.Bson.BsonSerializationException, MongoDB.Bson, Version=1.8.1.20, Culture=neutral, PublicKeyToken=f686731cfb9cc103

Can't deserialize a Quartz.IJobDetail with JobDetailImplSerializer.

   at Quartz.Impl.MongoDB.JobDetailImplSerializer.Deserialize(BsonReader bsonReader, Type nominalType, Type actualType, IBsonSerializationOptions options)
   at MongoDB.Bson.Serialization.Serializers.InterfaceSerializer.Deserialize(BsonReader bsonReader, Type nominalType, Type actualType, IBsonSerializationOptions options)
   at MongoDB.Bson.Serialization.Serializers.InterfaceSerializer.Deserialize(BsonReader bsonReader, Type nominalType, IBsonSerializationOptions options)
   at MongoDB.Driver.Internal.MongoReplyMessage`1.ReadFrom(BsonBuffer buffer, IBsonSerializationOptions serializationOptions)
   at MongoDB.Driver.Internal.MongoConnection.ReceiveMessage[TDocument](BsonBinaryReaderSettings readerSettings, IBsonSerializer serializer, IBsonSerializationOptions serializationOptions)
   at MongoDB.Driver.MongoCursorEnumerator`1.GetReply(MongoConnection connection, MongoRequestMessage message)
   at MongoDB.Driver.MongoCursorEnumerator`1.GetFirst()
   at MongoDB.Driver.MongoCursorEnumerator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at MongoDB.Driver.MongoCollection.FindOneAs[TDocument](IMongoQuery query)
   at MongoDB.Driver.MongoCollection.FindOneByIdAs[TDocument](BsonValue id)
   at Quartz.Impl.MongoDB.JobStore.RetrieveJob(JobKey jobKey)
   at Quartz.Impl.MongoDB.JobStore.StoreTrigger(IOperableTrigger newTrigger, Boolean replaceExisting)
   at Quartz.Impl.MongoDB.JobStore.StoreJobAndTrigger(IJobDetail newJob, IOperableTrigger newTrigger)
   at Quartz.Core.QuartzScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger) in c:\Work\OpenSource\Quartz.NET\quartznet\src\Quartz\Core\QuartzScheduler.cs:line 743
   at Quartz.Impl.StdScheduler.ScheduleJob(IJobDetail jobDetail, ITrigger trigger) in c:\Work\OpenSource\Quartz.NET\quartznet\src\Quartz\Impl\StdScheduler.cs:line 262

**Comment by Nanoko** [comment]
Hi, your fix has been merged.
Thanks for your help

**Comment by aleksandrov** [comment]
Np. Could you please update Nuget package as well?

Thanks
